name: Build iOS App (Optional)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    if: false # Set to true if you want iOS builds
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
    
    - name: Get Flutter dependencies
      run: flutter pub get
    
    - name: Build iOS (No Codesign)
      run: flutter build ios --release --no-codesign
    
    - name: Create IPA
      run: |
        mkdir -p build/ios/iphoneos/Payload
        cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
        cd build/ios/iphoneos/
        zip -r app-release.ipa Payload/
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: app-release-ipa
        path: build/ios/iphoneos/app-release.ipa
        retention-days: 30
