name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
    
    - name: Get Flutter dependencies
      run: flutter pub get
    
    - name: Run Flutter analyzer
      run: flutter analyze
    
    - name: Run Flutter tests
      run: flutter test --coverage
      continue-on-error: true
    
    - name: Build APK (Release)
      run: flutter build apk --release --verbose
    
    - name: Build APK (Debug) 
      run: flutter build apk --debug --verbose
      continue-on-error: true
    
    - name: Build App Bundle (AAB)
      run: flutter build appbundle --release --verbose
      continue-on-error: true
    
    - name: Get APK file info
      run: |
        echo "APK file size:"
        ls -lh build/app/outputs/flutter-apk/
        echo "APK file details:"
        file build/app/outputs/flutter-apk/app-release.apk
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: app-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 7
      continue-on-error: true
    
    - name: Upload App Bundle (AAB)
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-release-aab
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30
      continue-on-error: true
    
    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          ## 📱 Modern Form App Release
          
          ### What's New:
          - Beautiful Flutter UI with dark theme
          - Form validation and error handling
          - PHP backend integration
          - Submissions viewer
          
          ### 📥 Downloads:
          - **APK File**: Download from the artifacts below
          - **Size**: ~20-30 MB
          - **Min Android**: 5.0 (API 21)
          
          ### 🔧 Installation:
          1. Download the APK file
          2. Enable "Unknown Sources" in Android settings
          3. Install the APK
          
          Built automatically with GitHub Actions ✨
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Build for multiple architectures
  build-split-apk:
    name: Build Split APKs
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Get Flutter dependencies
      run: flutter pub get
    
    - name: Build Split APKs
      run: flutter build apk --split-per-abi --release
    
    - name: Upload ARM64 APK
      uses: actions/upload-artifact@v4
      with:
        name: app-arm64-v8a-release-apk
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        retention-days: 30
    
    - name: Upload ARM APK
      uses: actions/upload-artifact@v4
      with:
        name: app-armeabi-v7a-release-apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        retention-days: 30
    
    - name: Upload x86_64 APK
      uses: actions/upload-artifact@v4
      with:
        name: app-x86_64-release-apk
        path: build/app/outputs/flutter-apk/app-x86_64-release.apk
        retention-days: 30
      continue-on-error: true
